import test from 'node:test';
import assert from 'node:assert/strict';
import '../public/js/data.js';
import '../public/js/engine.js';
import '../public/js/storage.js';
import '../public/js/progression.js';
const G=globalThis.NightCourier;
const fresh=(mode='classic',seed=987654321)=>G.newGame('云行',mode,seed);
// Legacy gameplay scenarios now wait through the real simulation; no instant
// settlement entry point exists in production or tests.
const complete=s=>{for(let i=0;s.activity&&!s.pending&&!s.gameOver&&i<5000;i++)s=G.advance(s,Math.max(1e-7,Math.min(1,G.activityRemaining(s))));assert.ok(!s.activity||s.gameOver,'行动应当完成');return s;};
const near=(a,b)=>assert.ok(Math.abs(a-b)<1e-5,`${a} ≠ ${b}`);
const run=(s,action,p={})=>{const r=G.perform(s,action,p);assert.ok(r.ok,r.error);return complete(r.state);};
const rich=()=>{const s=fresh();s.player.money=10000;s.player.coins=10000;return s;};
const settle=s=>s.pending?run(s,'choose',{eventId:s.pending.id,index:0}):s;
class MemoryStorage{data=new Map();getItem(k){return this.data.get(k)??null;}setItem(k,v){this.data.set(k,String(v));}removeItem(k){this.data.delete(k);}}

test('创建存档：姓名、初始时间和模式固定',()=>{const s=G.newGame('  云行  ','ai',12);assert.equal(s.name,'云行');assert.equal(G.clock(s),'08:00');assert.equal(G.day(s),1);assert.equal(s.mode,'ai');assert.equal(G.perform(s,'setMode',{mode:'classic'}).ok,false);});
test('拒绝空姓名、超长姓名与无效模式',()=>{for(const name of ['','   ','名'.repeat(17)])assert.throws(()=>G.newGame(name));assert.throws(()=>G.newGame('云行','unknown'));});
test('地图包含 99 个唯一地点，其中 90 个是动态配送地点、3 个住处常驻',()=>{assert.equal(G.PLACES.length,99);assert.equal(G.PLACES.filter(p=>!p.permanent).length,90);assert.equal(G.RESIDENCES.length,3);assert.ok(G.RESIDENCES.every(h=>G.place(h.place)?.permanent));assert.equal(new Set(G.PLACES.map(p=>p.id)).size,99);});
test('同地点移动距离、时间、体力、电量全为零',()=>{const s=fresh(),p=G.travelPlan(s,'home');for(const k of ['meters','minutes','stamina','battery'])assert.equal(p[k],0);});
test('所有地点可达且路程对称',()=>{for(const a of G.PLACES)for(const b of G.PLACES){const r=G.route(a.id,b.id);assert.ok(Number.isFinite(r.meters));assert.equal(r.meters,G.route(b.id,a.id).meters);assert.deepEqual(r.points[0],{x:a.x,y:a.y});assert.deepEqual(r.points.at(-1),{x:b.x,y:b.y});}});
test('跨江线路只能走四座实际存在的桥',()=>{for(const a of G.PLACES)for(const b of G.PLACES){const points=G.route(a.id,b.id).points;for(let i=1;i<points.length;i++){const p=points[i-1],q=points[i];if(Math.min(p.x,q.x)===850&&Math.max(p.x,q.x)===1090){assert.equal(p.y,q.y);assert.ok([300,660,1020,1380].includes(p.y));}}}});
test('行程分钟由道路距离和速度计算',()=>{const s=fresh(),p=G.travelPlan(s,'temple');near(p.minutes,p.km/p.speed*60);assert.ok(p.meters>0);});
test('升级速度会缩短同一路段骑行时间',()=>{const s=fresh(),before=G.travelPlan(s,'temple');s.vehicle.levels.speed=5;const after=G.travelPlan(s,'temple');assert.ok(after.minutes<before.minutes);assert.equal(after.meters,before.meters);});
test('天气与步行身法会影响速度',()=>{const s=fresh(),clear=G.travelPlan(s,'temple');s.weather='rain';assert.ok(G.travelPlan(s,'temple').minutes>clear.minutes);s.transport='walk';const slow=G.travelPlan(s,'temple');s.learned.push('lightstep');assert.ok(G.travelPlan(s,'temple').minutes<slow.minutes);});
test('零电量不能骑行，失败不改变状态',()=>{const s=fresh();s.vehicle.battery=0;const before=JSON.stringify(s),r=G.perform(s,'travel',{target:'garage'});assert.equal(r.ok,false);assert.match(r.error,/没电/);assert.equal(r.state,s);assert.equal(JSON.stringify(s),before);});
test('不足以完成整段行程的电量也不能骑行',()=>{const s=fresh();s.vehicle.battery=.01;const r=G.perform(s,'travel',{target:'temple'});assert.equal(r.ok,false);assert.match(r.error,/电量不足/);assert.equal(s.position,'home');});
test('车况为零禁止骑行',()=>{const s=fresh();s.vehicle.durability=0;assert.equal(G.perform(s,'travel',{target:'garage'}).ok,false);});
test('步行推车不耗电，空电仍可去修车铺',()=>{let s=fresh();s.vehicle.battery=0;s=run(s,'transport',{mode:'walk'});s=run(s,'travel',{target:'garage'});assert.equal(s.position,'garage');assert.equal(s.vehicle.battery,0);});
test('移动结束时累计消耗、电量、路程与位置正确',()=>{const s=fresh(),p=G.travelPlan(s,'clinic'),after=run(s,'travel',{target:'clinic'});assert.equal(after.position,'clinic');near(after.minutes,s.minutes+p.minutes);near(after.player.stamina,s.player.stamina-p.stamina);assert.ok(Math.abs(after.vehicle.battery-(80-p.battery))<1e-8);near(after.stats.distance,p.meters);assert.equal(s.position,'home');});
test('体力不足不产生半途移动或负体力',()=>{const s=fresh();s.player.stamina=0;const r=G.perform(s,'travel',{target:'temple'});assert.equal(r.ok,false);assert.equal(r.state.minutes,s.minutes);});
test('行动后订单刷新，地点与 ID 不重复',()=>{const s=fresh(),ids=s.orders.map(o=>o.id),after=run(s,'rest');assert.equal(after.orders.length,6);assert.equal(new Set(after.orders.map(o=>o.target)).size,6);assert.ok(after.orders.every(o=>!ids.includes(o.id)&&o.target!==after.position));});
test('初次配送先抵达并保存事件，做选择后才发放现金和币',()=>{const s=fresh(),ticket=s.orders.find(o=>o.condition!=='careful')||s.orders[0];const accepted=run(s,'deliver',{id:ticket.id});assert.equal(accepted.position,ticket.target);assert.ok(accepted.pending);assert.equal(accepted.stats.delivered,0);assert.equal(accepted.player.coins,0);const done=run(accepted,'choose',{eventId:accepted.pending.id,index:0});assert.equal(done.stats.delivered,1);assert.equal(done.player.coins,ticket.coins);assert.equal(done.player.money,s.player.money+ticket.reward);assert.equal(done.pending,null);});
test('旧订单不能重复接取、事件不能重复结算',()=>{const s=fresh(),id=s.orders[0].id,accepted=run(s,'deliver',{id}),eventId=accepted.pending.id,done=run(accepted,'choose',{eventId,index:0});assert.equal(G.perform(done,'choose',{eventId,index:0}).ok,false);assert.equal(G.perform(done,'deliver',{id}).ok,false);assert.equal(done.stats.delivered,1);});
test('待处理事件期间阻止其他世界行动',()=>{const s=fresh(),p=run(s,'deliver',{id:s.orders[0].id});for(const action of ['rest','buy','transport','sleep','sign'])assert.equal(G.perform(p,action,{id:'qi',mode:'walk'}).ok,false);});
test('事件 ID 不匹配不能选择',()=>{const s=fresh(),p=run(s,'deliver',{id:s.orders[0].id});assert.equal(G.perform(p,'choose',{eventId:'stale-event',index:0}).ok,false);});
test('超时订单在出发前被拒绝',()=>{const s=fresh();s.orders[0].expiresAt=s.minutes;assert.equal(G.perform(s,'deliver',{id:s.orders[0].id}).ok,false);});
test('灵异订单需要灵力，易损订单需要保留体力',()=>{const s=fresh();s.orders[0].condition='mystic';s.player.mana=0;assert.equal(G.perform(s,'deliver',{id:s.orders[0].id}).ok,false);s.orders[0].condition='careful';s.player.stamina=G.travelPlan(s,s.orders[0].target).stamina+9;assert.equal(G.perform(s,'deliver',{id:s.orders[0].id}).ok,false);});
test('签到不耗时且每天只能领取一次',()=>{const s=fresh(),after=run(s,'sign');assert.equal(after.minutes,s.minutes);assert.equal(after.player.coins,5);assert.equal(G.perform(after,'sign').ok,false);});
test('连续签到在跨日后正确增长',()=>{let s=run(fresh(),'sign');s.minutes=1430;s=run(s,'rest');s=run(s,'sign');assert.equal(s.daily.streak,2);assert.equal(s.player.coins,11);});
test('系统兑换即时生效、不移动位置且不耗时',()=>{const s=rich(),after=run(s,'buy',{id:'qi'});assert.equal(after.position,s.position);assert.equal(after.minutes,s.minutes);assert.equal(after.inventory.qi,s.inventory.qi+1);assert.equal(after.player.coins,s.player.coins-5);});
test('外卖币不足不能兑换，不出现负数',()=>{const s=fresh(),r=G.perform(s,'buy',{id:'qi'});assert.equal(r.ok,false);assert.equal(r.state.player.coins,0);});
test('永久心法与法器按境界开放且不能重复兑换',()=>{let s=rich();assert.equal(G.perform(s,'buy',{id:'breathing'}).ok,false);s.player.realm=1;for(const id of ['breathing','lightstep']){s=run(s,'buy',{id});assert.equal(G.perform(s,'buy',{id}).ok,false);}assert.equal(G.perform(s,'buy',{id:'jade'}).ok,false);s.player.realm=2;for(const id of ['jade','robe']){s=run(s,'buy',{id});assert.equal(G.perform(s,'buy',{id}).ok,false);}assert.equal(G.limits(s).mana,122);assert.equal(G.limits(s).health,149);});
test('物品使用消耗数量，满属性时不浪费药品',()=>{const s=fresh(),r=G.perform(s,'use',{id:'heal'});assert.equal(r.ok,false);assert.equal(s.inventory.heal,1);const after=run(s,'use',{id:'qi'});assert.equal(after.inventory.qi,0);assert.equal(after.player.qi,35);assert.equal(after.minutes,s.minutes);});
test('主线与每日委托只能领奖一次',()=>{let s=fresh();s.stats.delivered=5;s.daily.delivered=3;s=run(s,'claim',{id:'q1'});assert.equal(G.perform(s,'claim',{id:'q1'}).ok,false);s=run(s,'claim',{id:'daily'});assert.equal(G.perform(s,'claim',{id:'daily'}).ok,false);});
test('未达到条件不发放主线奖励',()=>{assert.equal(G.perform(fresh(),'claim',{id:'q4'}).ok,false);});
test('跨日重置每日配送数和领取状态',()=>{let s=fresh();s.minutes=1430;s.daily.delivered=8;s.daily.claimed=true;s=run(s,'rest');assert.equal(G.day(s),2);assert.equal(s.daily.delivered,0);assert.equal(s.daily.claimed,false);});
test('夜间修炼获得更多修为，灵地额外提高收益',()=>{const day=fresh(),night=fresh(),temple=fresh();night.minutes=1200;temple.minutes=1200;temple.position='temple';const a=run(day,'cultivate',{kind:'breath'}),b=run(night,'cultivate',{kind:'breath'}),c=run(temple,'cultivate',{kind:'breath'});assert.ok(b.player.qi>a.player.qi);assert.ok(c.player.qi>b.player.qi);assert.equal(a.minutes-day.minutes,45);});
test('心法加成提高修炼收益',()=>{const a=fresh(),b=fresh();b.learned.push('breathing');assert.ok(run(b,'cultivate',{kind:'meditate'}).player.qi>run(a,'cultivate',{kind:'meditate'}).player.qi);});
test('破境丹改善概率但不能突破概率上限',()=>{const s=fresh();assert.ok(G.breakChance(s,true)>G.breakChance(s,false));s.player.insight=99;s.player.karma=100;assert.equal(G.breakChance(s,true),95);});
test('突破的成功与失败路径均会实际执行',()=>{let success=false,failure=false;for(let seed=1;seed<100;seed++){const s=fresh('classic',seed);s.player.qi=80;const a=run(s,'breakthrough');if(a.player.realm===1){success=true;assert.equal(a.player.qi,0);}else{failure=true;assert.equal(a.player.qi,60);assert.equal(a.player.health,82);}if(success&&failure)break;}assert.ok(success&&failure);});
test('护身符在突破失败时保护气血并消耗',()=>{let found=false;for(let seed=1;seed<100;seed++){const s=fresh('classic',seed);s.player.qi=80;s.inventory.charm=1;const a=run(s,'breakthrough');if(a.player.realm===0){assert.equal(a.player.health,100);assert.equal(a.inventory.charm,0);found=true;break;}}assert.ok(found);});
test('没有破境丹时不能凭参数无偿增加成功率',()=>{const s=fresh();s.player.qi=100;assert.equal(G.perform(s,'breakthrough',{usePill:true}).ok,false);});
test('睡觉补满体力、灵力与电量，按返家路程加睡眠计时',()=>{const s=fresh();s.position='garage';s.player.stamina=70;s.player.mana=5;s.vehicle.battery=50;const plan=G.travelPlan(s,'home'),a=run(s,'sleep');near(a.minutes,s.minutes+plan.minutes+480);assert.equal(a.position,'home');assert.equal(a.vehicle.battery,G.limits(a).battery);assert.equal(a.player.stamina,G.limits(a).stamina);});
test('充电可在任意地点直接进行，收费且耗时',()=>{const s=fresh();s.vehicle.battery=0;s.position='park';const a=run(s,'charge');assert.equal(a.position,'park');assert.equal(a.vehicle.battery,80);assert.equal(a.player.money,112);assert.equal(a.minutes,490);});
test('电动车三种升级独立保存且有等级上限',()=>{let s=rich();s.position='garage';for(const kind of ['speed','battery','durability'])for(let i=0;i<5;i++)s=run(s,'upgrade',{kind});assert.deepEqual(s.vehicle.levels,{speed:5,battery:5,durability:5});assert.equal(G.perform(s,'upgrade',{kind:'speed'}).ok,false);const restored=G.sanitizeSave(JSON.parse(JSON.stringify(s)));assert.deepEqual(restored.vehicle.levels,s.vehicle.levels);assert.equal(restored.vehicle.battery,s.vehicle.battery);});
test('每七天按当前住处扣除完整房租',()=>{let s=fresh();s.minutes=6*1440-20;s.player.money=200;s=run(s,'rest');assert.equal(G.day(s),7);assert.equal(s.player.money,80);assert.equal(s.gameOver,null);});
test('房租到期现金不足时立即结束本局',()=>{let s=fresh();s.minutes=6*1440-20;s.player.money=119;s=run(s,'rest');assert.equal(G.day(s),7);assert.equal(s.player.money,119);assert.equal(s.gameOver?.reason,'rent');assert.equal(s.gameOver?.rent,120);assert.equal(G.perform(s,'rest').ok,false);});
test('搬家使用真实路程并改变后续房租',()=>{let s=fresh();const home=G.residence('qiyun'),plan=G.travelPlan(s,home.place);s=run(s,'moveHome',{id:'qiyun'});assert.equal(s.residenceId,'qiyun');assert.equal(s.position,home.place);near(s.minutes,480+plan.minutes);s.minutes=6*1440-20;s.player.money=80;s=run(s,'rest');assert.equal(s.player.money,10);assert.equal(s.gameOver,null);});
test('不同住处的睡眠恢复不同',()=>{let cheap=fresh();cheap.player.health=40;cheap.player.stamina=10;cheap.player.mana=5;cheap.vehicle.battery=10;cheap.residenceId='qiyun';cheap.position=G.residence('qiyun').place;const cheapAfter=run(cheap,'sleep');near(cheapAfter.player.health,60);near(cheapAfter.player.stamina,80);near(cheapAfter.player.mana,15);assert.equal(cheapAfter.vehicle.battery,10);let premium=fresh();premium.player.health=40;premium.player.stamina=10;premium.player.mana=5;premium.vehicle.battery=10;premium.residenceId='songfeng';premium.position=G.residence('songfeng').place;const premiumAfter=run(premium,'sleep'),caps=G.limits(premiumAfter);assert.equal(premiumAfter.player.health,caps.health);assert.equal(premiumAfter.player.stamina,caps.stamina);assert.equal(premiumAfter.player.mana,caps.mana);assert.equal(premiumAfter.vehicle.battery,caps.battery);});
test('炼丹需要材料与灵力，不足时不消耗时间',()=>{const s=fresh();assert.equal(G.perform(s,'alchemy',{recipe:'qi'}).ok,false);s.inventory.herb=2;const a=run(s,'alchemy',{recipe:'qi'});assert.equal(a.inventory.herb,0);assert.equal(a.player.mana,50);assert.equal(a.minutes,s.minutes+25);});
test('未结识 NPC 不可直接拜访',()=>{const s=fresh();assert.equal(s.bonds.chen.met,false);const r=G.perform(s,'visit',{id:'chen'});assert.equal(r.ok,false);assert.match(r.error,/还没有.*结识/);});
test('配送到 NPC 所在地点后解锁羁绊',()=>{let s=fresh();s.flags.firstOrder=true;s.orders=[{id:'npc-order',target:'garage',title:'送到修车铺的热饭',desc:'趁热送到。',condition:'ordinary',expiresAt:s.minutes+180,reward:20,coins:2,npc:'chen'}];s=run(s,'deliver',{id:'npc-order'});s=settle(s);assert.equal(s.bonds.chen.met,true);assert.ok(s.bonds.chen.affinity>=3);});
test('随机配送奇遇可以结识隐藏 NPC',()=>{let found=false;for(let seed=1;seed<800&&!found;seed++){let s=fresh('classic',seed);s.flags.firstOrder=true;s.player.luck=99;s.orders=[{id:'rival-order',target:'stop-0',title:'普通配送',desc:'测试订单',condition:'ordinary',expiresAt:s.minutes+180,reward:20,coins:2,npc:null}];const r=G.perform(s,'deliver',{id:'rival-order'});if(r.ok)r.state=complete(r.state);if(r.ok&&r.state.pending?.templateId==='rival'){assert.equal(r.state.bonds.zhou.met,true);found=true;}}assert.ok(found,'应能在随机配送奇遇中遇见周野');});
test('旧存档用既有关系进度推断已结识状态',()=>{const s=fresh();delete s.bonds.lin.met;s.bonds.lin.affinity=6;const a=G.sanitizeSave(JSON.parse(JSON.stringify(s)));assert.equal(a.bonds.lin.met,true);assert.equal(a.bonds.su.met,false);});
test('人物故事在选择后推进，当天无法反复深入交谈',()=>{let s=fresh();s.bonds.chen.met=true;s=run(s,'visit',{id:'chen'});assert.equal(s.position,'garage');assert.equal(s.bonds.chen.stage,0);s=run(s,'choose',{eventId:s.pending.id,index:0});assert.equal(s.bonds.chen.stage,1);assert.equal(G.perform(s,'visit',{id:'chen'}).ok,false);});
test('人物友情和情感线路由明确选择决定',()=>{for(const index of [0,1]){let s=rich();Object.assign(s.bonds.lin,{met:true,affinity:45,trust:20,stage:3});s=run(s,'visit',{id:'lin'});s=run(s,'choose',{eventId:s.pending.id,index});assert.equal(s.bonds.lin.path,index===1?'romance':'friend');assert.equal(s.bonds.lin.stage,4);}});
test('选择需要的材料不足时不能被结算',()=>{let s=rich();Object.assign(s.bonds.lin,{met:true,affinity:25,trust:10,stage:2});s.inventory.heal=0;s=run(s,'visit',{id:'lin'});assert.equal(G.perform(s,'choose',{eventId:s.pending.id,index:1}).ok,false);});
test('不满足条件不能触发结局，满足后可继续游历',()=>{let s=fresh();assert.equal(G.perform(s,'finale',{id:'guardian'}).ok,false);s.stats.delivered=25;s.player.realm=2;s.player.karma=10;s.inventory.fragment=3;s=run(s,'finale',{id:'guardian'});assert.equal(s.ending,'guardian');assert.equal(G.perform(s,'rest').ok,false);s=run(s,'continue');assert.equal(s.ending,null);assert.ok(s.unlockedEndings.includes('guardian'));});
test('气血降至零时触发救助而非产生不可玩状态',()=>{let found=false;for(let seed=1;seed<100;seed++){const s=fresh('classic',seed);s.player.qi=80;s.player.health=1;const a=run(s,'breakthrough');if(a.player.realm===0){assert.equal(a.position,'clinic');assert.equal(a.player.health,45);assert.ok(a.player.stamina>=35);found=true;break;}}assert.ok(found);});
const validAI=()=>({title:'雨后的灯',text:'巷口的人在等一份热饭。',choices:[{label:'停下来听他说完',result:'你们相视一笑。',effects:{qi:5}},{label:'买一杯热茶',result:'夜晚暖了一点。',effects:{money:-5,karma:2}},{label:'留下祝福',result:'你认真说了再见。',effects:{rep:1}}]});
test('AI 事件接受有界的三个选项',()=>{assert.equal(G.validateAIEvent(validAI()).choices.length,3);});
test('AI 拒绝越权属性、过大收益、浮点数与过多选项',()=>{for(const effects of [{realm:5},{coins:999},{qi:1.5}]){const raw=validAI();raw.choices[0].effects=effects;assert.throws(()=>G.validateAIEvent(raw));}const raw=validAI();raw.choices.push(raw.choices[0]);assert.throws(()=>G.validateAIEvent(raw));});
test('AI 必须提供一个完全无成本选项',()=>{const raw=validAI();for(const c of raw.choices)c.effects={money:-1};assert.throws(()=>G.validateAIEvent(raw));});
test('AI 异步结果只应用于相同且待生成的事件',()=>{let s=fresh('ai');s.flags.firstOrder=true;s.position='park';s=run(s,'explore');const id=s.pending.id;assert.equal(G.applyAIEvent(s,'wrong-id',validAI()),s);const a=G.applyAIEvent(s,id,validAI());assert.equal(a.pending.source,'ai');assert.equal(a.pending.aiStatus,'success');assert.equal(G.applyAIEvent(a,id,validAI()),a);assert.equal(a.minutes,s.minutes);});
test('AI 回退保留模式、事件和原有数值',()=>{let s=fresh('ai');s.position='park';s=run(s,'explore');const a=G.fallbackAI(s,s.pending.id,'未配置');assert.equal(a.mode,'ai');assert.equal(a.pending.title,s.pending.title);assert.equal(a.pending.aiStatus,'fallback');assert.equal(a.player.money,s.player.money);});
test('已选择的事件不接受迟到的 AI 回包',()=>{let s=fresh('ai');s.position='park';s=run(s,'explore');const id=s.pending.id;s=settle(s);assert.equal(G.applyAIEvent(s,id,validAI()),s);});
test('相同存档的相同行动产生相同的随机结果',()=>{const s=fresh(),a=run(s,'cultivate',{kind:'breath'}),b=run(G.clone(s),'cultivate',{kind:'breath'});assert.equal(a.seed,b.seed);assert.deepEqual(a.orders,b.orders);assert.deepEqual(a.pending,b.pending);assert.deepEqual(a.player,b.player);});
test('待处理配送事件跨读档只能结算一次',()=>{let s=fresh();s=run(s,'deliver',{id:s.orders[0].id});const restored=G.sanitizeSave(JSON.parse(JSON.stringify(s)));assert.equal(restored.pending.id,s.pending.id);assert.equal(restored.pending.delivery.id,s.pending.delivery.id);const done=run(restored,'choose',{eventId:restored.pending.id,index:0});assert.equal(done.stats.delivered,1);assert.equal(G.perform(done,'choose',{eventId:s.pending.id,index:0}).ok,false);});
test('NPC 待选择章节跨读档保持选项和进度',()=>{let s=fresh();s.bonds.shen.met=true;s=run(s,'visit',{id:'shen'});const a=G.sanitizeSave(JSON.parse(JSON.stringify(s)));assert.equal(a.bonds.shen.stage,0);assert.equal(a.pending.choices.length,3);assert.deepEqual(a.pending.choices,s.pending.choices);});
test('重建版 v1 / v2 / v3 存档升级不重置人物及电动车，并默认青藤小屋',()=>{for(const version of [1,2,3]){const s=rich();s.schemaVersion=version;delete s.residenceId;s.player.realm=3;s.vehicle.levels.speed=3;const a=G.sanitizeSave(s);assert.equal(a.schemaVersion,5);assert.equal(a.vehicle.levels.speed,3);assert.equal(a.player.realm,3);assert.equal(a.residenceId,'qingteng');assert.equal(a.name,s.name);}});
test('未知或未来版本不被盲目升级',()=>{const s=fresh();s.schemaVersion=9;assert.throws(()=>G.sanitizeSave(s));delete s.schemaVersion;assert.throws(()=>G.sanitizeSave(s));});
test('导入做数值边界与字段白名单处理',()=>{const s=fresh();s.player.money=-100;s.player.insight=1e9;s.vehicle.levels.speed=99;s.position='nowhere';s.residenceId='invalid-home';s.inventory.unknown=123;const a=G.sanitizeSave(s);assert.equal(a.player.money,0);assert.equal(a.player.insight,99);assert.equal(a.vehicle.levels.speed,5);assert.equal(a.position,'home');assert.equal(a.residenceId,'qingteng');assert.equal(a.inventory.unknown,undefined);});
test('JSON 中的原型字段不会污染对象',()=>{const raw=JSON.parse(G.exportSaves([fresh()]).replace('"player": {','"__proto__": {"polluted": true}, "player": {'));G.parseImport(JSON.stringify(raw));assert.equal({}.polluted,undefined);});
test('多存档保存和读取保留彼此进度',()=>{const memory=new MemoryStorage(),a=G.createStore(memory);a.load();const s1=fresh(),s2=G.newGame('青禾','ai',22);assert.ok(a.upsert(s1).ok);assert.ok(a.upsert(s2).ok);const b=G.createStore(memory);const saves=b.load();assert.equal(saves.length,2);assert.deepEqual(new Set(saves.map(s=>s.mode)),new Set(['classic','ai']));});
test('旧版本存储键会迁移到 v5 且保留存档',()=>{const memory=new MemoryStorage(),old=fresh();old.schemaVersion=3;delete old.residenceId;memory.setItem(G.LEGACY_STORAGE_KEY,JSON.stringify({schemaVersion:3,saves:[old]}));const store=G.createStore(memory),saves=store.load();assert.equal(saves.length,1);assert.equal(saves[0].schemaVersion,5);assert.equal(saves[0].residenceId,'qingteng');assert.ok(memory.getItem(G.STORAGE_KEY));});
test('导入默认新副本，不覆盖原有同 ID 存档',()=>{const store=G.createStore(new MemoryStorage()),s=fresh();store.load();store.upsert(s);const r=store.import(G.exportSaves([s]));assert.ok(r.ok);assert.equal(store.saves.length,2);assert.notEqual(store.saves[0].id,store.saves[1].id);});
test('超过存档上限时拒绝新增而非覆盖',()=>{const store=G.createStore(new MemoryStorage());store.load();for(let i=0;i<G.MAX_SAVES;i++)assert.ok(store.upsert(fresh()).ok);assert.equal(store.upsert(fresh()).ok,false);assert.equal(store.saves.length,G.MAX_SAVES);});
test('主记录损坏时从上一次备份恢复，不覆盖原始损坏文本',()=>{const memory=new MemoryStorage(),store=G.createStore(memory);store.load();let s=fresh();store.upsert(s);s=run(s,'sign');store.upsert(s);memory.setItem(G.STORAGE_KEY,'broken data');const reader=G.createStore(memory),saves=reader.load();assert.equal(saves.length,1);assert.equal(saves[0].player.coins,0);assert.match(reader.warning,/备份/);assert.equal(memory.getItem(G.STORAGE_KEY),'broken data');});
test('存储失败明确报告，并保留可导出的内存进度',()=>{const memory=new MemoryStorage();memory.setItem=()=>{throw Object.assign(new Error('quota'),{name:'QuotaExceededError'});};const store=G.createStore(memory);store.load();const s=fresh();const r=store.upsert(s);assert.equal(r.ok,false);assert.equal(store.saves[0].id,s.id);assert.equal(store.unavailable,true);});
test('完全禁止本地存储也能在当前页进行游戏',()=>{const store=G.createStore(null);store.load();const s=fresh();assert.equal(store.upsert(s).ok,false);assert.equal(store.saves[0].id,s.id);});
test('混合有效和损坏存档的导入具有原子性',()=>{const store=G.createStore(new MemoryStorage());store.load();store.upsert(fresh());assert.throws(()=>store.import(JSON.stringify({saves:[fresh(),{bad:true}]})));assert.equal(store.saves.length,1);});
test('损坏 JSON、超大文件与空包不会被导入',()=>{assert.throws(()=>G.parseImport('no'));assert.throws(()=>G.parseImport(' '.repeat(2*1024*1024+1)));assert.throws(()=>G.parseImport('{"saves":[]}'));});
test('主动恢复自动备份回到上一次写入前的进度',()=>{const memory=new MemoryStorage(),store=G.createStore(memory);store.load();const s=fresh();store.upsert(s);store.upsert(run(s,'sign'));assert.equal(store.saves[0].player.coins,5);assert.ok(store.restoreBackup().ok);assert.equal(store.saves[0].player.coins,0);});
test('NPC 每一章节都有资源耗尽时仍可选的路线，避免软锁',()=>{const s=fresh();s.player.money=0;s.player.coins=0;s.player.mana=0;s.player.stamina=0;for(const k of Object.keys(s.inventory))s.inventory[k]=0;for(const n of G.NPCS)for(const arc of n.arc){const choices=arc.slice(2);s.pending={npcId:n.id};assert.ok(choices.some(c=>!G.choiceBlock(s,c)),`${n.name} / ${arc[0]} 会锁死`);}});
test('存储失败后返回菜单重新 load 不会丢失未写入的内存进度',()=>{const mem=new MemoryStorage(),store=G.createStore(mem);store.load();const s=fresh();store.upsert(s);mem.setItem=()=>{throw Object.assign(new Error('quota'),{name:'QuotaExceededError'});};const newer=run(s,'sign');assert.equal(store.upsert(newer).ok,false);assert.equal(store.load()[0].player.coins,5);});
test('成长阶段会随配送、境界和人物关系推进',()=>{const s=fresh();assert.equal(G.storyStage(s).id,'mortal');s.flags.firstOrder=true;assert.equal(G.storyStage(s).id,'bound');s.stats.delivered=8;s.player.realm=1;assert.equal(G.storyStage(s).id,'second-city');s.bonds.chen.met=true;s.bonds.lin.met=true;assert.equal(G.storyStage(s).id,'circle');s.stats.delivered=18;s.player.realm=2;assert.equal(G.storyStage(s).id,'guardian');});
test('达到阈值后自动进入固定主线事件，AI 存档也不覆盖关键剧情',()=>{let s=fresh('ai');s.flags.firstOrder=true;s.stats.delivered=3;s=run(s,'rest');assert.equal(s.pending.templateId,'story-street-vein');assert.equal(s.pending.source,'classic');assert.equal(s.pending.aiStatus,'skip');assert.equal(s.flags.storyStreetVein,true);});
test('主线标记和待选关键事件跨读档保留',()=>{let s=fresh();s.flags.firstOrder=true;s.stats.delivered=3;s=run(s,'rest');const restored=G.sanitizeSave(JSON.parse(JSON.stringify(s)));assert.equal(restored.flags.storyStreetVein,true);assert.equal(restored.pending.templateId,'story-street-vein');const done=run(restored,'choose',{eventId:restored.pending.id,index:0});assert.equal(done.pending,null);});
test('系统高级兑换需要境界，失败不扣外卖币',()=>{let s=rich();const before=s.player.coins,r=G.perform(s,'buy',{id:'foundation'});assert.equal(r.ok,false);assert.equal(r.state.player.coins,before);s.player.realm=1;s=run(s,'buy',{id:'foundation'});assert.equal(s.inventory.foundation,1);});
test('新增核心人物也能通过随机奇遇被发现',()=>{const ids=new Set(G.EVENTS.filter(e=>e.encounterNpc).map(e=>e.encounterNpc));for(const id of ['lin','chen','shen','lu','zhou','su'])assert.ok(ids.has(id),id+' 缺少奇遇入口');});
test('高机缘在同一组随机种子中发现更多额外材料',()=>{let low=0,high=0;for(let seed=100;seed<250;seed++){const a=fresh('classic',seed),b=fresh('classic',seed);a.position='park';b.position='park';a.player.luck=1;b.player.luck=40;low+=run(a,'explore').inventory.herb;high+=run(b,'explore').inventory.herb;}assert.ok(high>low,`${high} 应大于 ${low}`);});
test('连续游玩可送达 40 单并达成守城结局，流程无死局',()=>{let s=fresh();for(let i=0;i<750;i++){
  if(s.pending){const choices=s.pending.choices.map((c,index)=>({c,index})).filter(x=>!G.choiceBlock(s,x.c));assert.ok(choices.length,'任何事件都必须至少有一个可用选择');choices.sort((a,b)=>((b.c.effects.karma||0)*2+(b.c.effects.qi||0))-((a.c.effects.karma||0)*2+(a.c.effects.qi||0)));s=run(s,'choose',{eventId:s.pending.id,index:choices[0].index});continue;}
  if(s.stats.delivered>=40&&s.player.realm>=3&&(s.inventory.fragment||0)>=3&&s.player.karma>=5)break;
  const q=G.QUESTS.find(q=>!s.claimed.includes(q.id)&&G.questReady(s,q));if(q){s=run(s,'claim',{id:q.id});continue;}
  if(s.inventory.qi>0){s=run(s,'use',{id:'qi'});continue;}
  if(s.player.qi>=G.REALMS[s.player.realm].need&&G.REALMS[s.player.realm].need&&s.player.stamina>=20){s=run(s,'breakthrough');continue;}
  if(s.player.coins>=5&&s.player.realm<3){s=run(s,'buy',{id:'qi'});continue;}
  if((s.inventory.fragment||0)<3&&s.player.coins>=8&&s.stats.delivered>=25){s=run(s,'buy',{id:'fragment'});continue;}
  if(s.vehicle.battery<30||s.player.stamina<30){if(G.travelBlock(s,G.travelPlan(s,'home'))){s=run(s,'transport',{mode:'walk'});if(G.travelBlock(s,G.travelPlan(s,'home'))){s=run(s,'rest');continue;}}s=run(s,'sleep');s=run(s,'transport',{mode:'bike'});continue;}
  const orders=[...s.orders].sort((a,b)=>G.travelPlan(s,a.target).minutes-G.travelPlan(s,b.target).minutes);let moved=false;for(const o of orders){const r=G.perform(s,'deliver',{id:o.id});if(r.ok){s=complete(r.state);moved=true;break;}}if(!moved)s=run(s,'rest');
  for(const key of ['health','stamina','mana','money','coins','qi'])assert.ok(Number.isFinite(s.player[key])&&s.player[key]>=0);
}assert.ok(s.stats.delivered>=40);assert.ok(s.player.realm>=3);assert.ok(G.endingOptions(s).find(e=>e.id==='guardian').ready);s=run(s,'finale',{id:'guardian'});assert.equal(s.ending,'guardian');});
